apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: weary-backend-tls
  namespace: weary-backend
spec:
  secretName: weary-backend-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - backend.weary.app
