apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/LukMayr/k8s/
    path: root
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
