apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: weary-backend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/LukMayr/k8s/
    path: weary-backend
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: weary-backend
