apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: weary-waitlist-tls
  namespace: weary-backend
spec:
  secretName: weary-waitlist-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - waitlist.weary.app
